model_dir: logs/train_EC_2024_10_25__13_26_04
lookup_data: data/ec_new/swissprot_ec_complete_by2022-05-25.pt
test_data: data/ec_new/swissprot_ec_complete_after_2022-05-25_filtered.pt
label_file: data/ec_new/ec_list_by2022-05-25.json
topk: 1
ont: ec